### ISSUE TITLE
Todo: object rendering to see 3D relief

### ISSUE THREAD

**Issue by foulonj** [foulonj/glic#3]

**Comment by loicNorgeot** [comment]
CF:
http://opengl.developpez.com/tutoriels/opengl-tutorial/8-shaders-de-base/

Super tuto sur la réalisation de shaders assez simples permettant un rendu "Réaliste".

**Comment by foulonj** [comment]
Ok merci !

Le 14 août 2015 à 18:11, loicNorgeot <notifications@github.com<mailto:notifications@github.com>> a écrit :

CF:
http://opengl.developpez.com/tutoriels/opengl-tutorial/8-shaders-de-base/

Super tuto sur la réalisation de shaders assez simples permettant un rendu "Réaliste".

**Comment by loicNorgeot** [comment]
Je suis en train de mettre ça en route...

**Comment by loicNorgeot** [comment]
Issue fermée, il ne reste "plus qu'à" gérer les vertex qui n'ont pas d'indication de normale dans les maillages pour éviter les patchs grisés sur l'objet.
